version: '3.8'
services:
  guacd:
    image: guacamole/guacd
    restart: always

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-p${DB_ROOT_PASSWORD}", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "3306:3306"
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
    #  - guacamole_db:/var/lib/mysql
    restart: always

  guacamole:
    image: guacamole/guacamole
    depends_on:
      guacd:
        condition: service_started
      mysql:
        condition: service_healthy
    ports:
      - "8005:8080"
    environment:
      GUACD_HOSTNAME: guacd
      MYSQL_HOSTNAME: mysql
      MYSQL_DATABASE: '${DB_NAME}'
      MYSQL_USER: '${DB_USER}'
      MYSQL_PASSWORD: '${DB_PASSWORD}'
      MYSQL_DRIVER: mysql
      MYSQL_SSL_MODE: disabled
    links:
      - guacd
    restart: always

